---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1d7aveag80txjvmsswkyjqr7w8p9x99gxv5n4fjf9qjzu59qtwfrsljj7zt
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1d7aveag80txjvmsswkyjqr7w8p9x99gxv5n4fjf9qjzu59qtwfrsljj7zt
