# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:lxlssEM+BXqzEpViR1YYWxq6rW9e9XY=,iv:Q5cec2mpEVGv06gzcYGVaALg9OZ/GrjJMCqy+eXi/Hc=,tag:OIY6+R+TE6ZRhl8myC4k6A==,type:str]
    api-key: ENC[AES256_GCM,data:zYquHafACNt0iSJ+wt5et1rqKtk05sx/xE5clOCXl5msy7arOQ==,iv:GSbrXoAh8hRTOpp5n9xKE9TrpSv1mmDoVnYOLWO0gMM=,tag:jJMxPT3ou94+gycUzgrn3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d7aveag80txjvmsswkyjqr7w8p9x99gxv5n4fjf9qjzu59qtwfrsljj7zt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueFZodVBybHVxaDJNVk5N
            NmhManlzQ0pKMDZLS3ZaeVkzZk93OHJ1WUZFCnMzMjc0SUJIcVkvbEQwMDJqMU9G
            RjVWRDhZais5VXFFRVNQbWZkendZWXMKLS0tIFJzeFgyQmZzMmIvWDF2S3BSOEpO
            SFY5NG9FaS9yZm92VEsvL0hYQ05jdHMK1Ebf8WnQjKfjQ9QRDCbuIA8YaF6n56bb
            ktewmevRq3jpDqP6lTo22YqBDu3MDY7NYnT0OpwJgdTbxP9bY4f58w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-09T14:08:27Z"
    mac: ENC[AES256_GCM,data:WU5KxjtKnqhqUx7FtlCl+gR6qHJCsF+QAm3xLl+gZXCgU1sxIU/LvxkY1m+k2val8dwQgE/IqFTjcun6j0tsXxX0oo9B+j1+ElYmAVWi3IuCBwvl9+giVwc9/0dELVqGuC4WGm3iAHT2QnvL9APm2ZyzTljolIZEoHi92aOAyzw=,iv:xfJR0baCiF0az82mIr5Wltb3dYc/bHNq2D3cqJ2caJU=,tag:FCgCBq1kjk7XIZI3sqiLvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
