# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:PbcKqV3yTaKHkJz8xA==,iv:8dOamGBxgtNUr2H8+9/UOFVREpso/P6uzzR6pyaBZd4=,tag:RcoO4U6bEwXE3COPuJH2Kw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:IjjrYCq5XreiPUahk5PLafXeu1oTgf4=,iv:iBmuKdjvIKIh+s5JzaHY7dISOmPd4EMhNMCPFu/BT10=,tag:3oECTWHlTp7V8uUtvco7Gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d7aveag80txjvmsswkyjqr7w8p9x99gxv5n4fjf9qjzu59qtwfrsljj7zt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ1MrVWZNclptdG1Pd3JN
            Nk0wejBTQis2ODdlVjhGVWsvYVN3UVA4bkdNClV1TlNjdmJmVnJoZldOMGlzdDhr
            N0dPOEt5c29Gejd5RzFzNW0zcjdKY0kKLS0tIFNKSGZpbHNRV3RYTzNvSDVuRGtB
            OFAvV0t1V2hhTG1NMlZLVFFqLzBUcmsKpz1UfDPw1v3SfoL66Y0cRm8qJJ28O4i4
            srCTbDbusugIKKazCnGzLP0MnD71x3T7NO4ilk5XmBbffrQE8mnGWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-09T14:08:26Z"
    mac: ENC[AES256_GCM,data:rJ2F+X/nwhNlLQYxHU0KowpwblXu2iCSApmZueLrEALzx5/naCBA9FmyAu2euoks2+YgwoIu5T1FvLQmyTtDB4RTC51cj4EPbFjeZMYc0OCT9n6NeB2S/OAplPQ6chtqkpQZOvQXwNlmZemXL6Rs4N46xI35b2YGbIG2c+LjiBg=,iv:QL4wttPxkiPVqcheVpjppmmbPZwQn2rbl7XhLMLFUDA=,tag:HX6gGczmg6TYeJdTJLXJMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
