---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Etc/UTC
  METALLB_LB_RANGE: 192.168.1.200-192.168.1.240
  METALLB_K8S_GATEWAY_ADDR: 192.168.1.200
  METALLB_TRAEFIK_ADDR: 192.168.1.201
